name: ğŸ› ï¸ Update Codeforces Stats

on:
  schedule:
    - cron: '* */12 * * *'  # every day at 12:00 AM UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout Repo
        uses: actions/checkout@v3

      - name: ğŸ”§ Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: ğŸ“¦ Install dependencies
        run: pip install requests

      - name: ğŸ§  Run Codeforces Stats Script
        run: python scripts/update_readme.py
        env:
          CF_USERNAME: patilmadhuram
          
      - name: ğŸ’¾ Commit & Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m 'â™»ï¸ Update Codeforces stats'
          git push
